version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"

  bot:
    build: .
    restart: always
    network_mode: host          # <-- ключевая строка
    volumes:
      - .:/app
    working_dir: /app
    env_file: .env
    environment:
      - NO_PROXY=127.0.0.1,localhost,qdrant,85.208.208.39
      - no_proxy=127.0.0.1,localhost,qdrant,85.208.208.39
      - QDRANT_URL=http://127.0.0.1:6333   # если bot в host-сети
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
      - EMBED_MODEL=${EMBED_MODEL}
    # depends_on и extra_hosts больше не нужны при host-сети

