services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"

  bot:
    build: .
    network_mode: host
    container_name: jobradar-ai-bot
    restart: always
    working_dir: /app
    volumes:
      - .:/app                      # код проекта
      - ./hf_cache:/root/.cache/huggingface   # кэш моделей HF (сохраняется между запусками)
      - ./models:/models
    depends_on:
      - qdrant
    env_file: .env
    environment:
      # переменные моделей
      EMBED_MODEL: "${EMBED_MODEL:-deepvk/USER-bge-m3}"
      TRANSFORMERS_CACHE: "/root/.cache/huggingface"
      HF_HOME: "/root/.cache/huggingface"
      MODEL_DIR: "/models/USER-bge-m3"  # <— укажем локальный путь
      # прокси (если используешь SOCKS5 на 127.0.0.1:1080; можно держать пустыми)
      HTTP_PROXY: "${HTTP_PROXY}"
      HTTPS_PROXY: "${HTTPS_PROXY}"
      # важное: локальные адреса не через прокси
      NO_PROXY: "127.0.0.1,localhost,qdrant,85.208.208.39,huggingface.co,cdn-lfs.huggingface.co"
      # конфиг приложения
      QDRANT_URL: "${QDRANT_URL}"                 # напр. http://qdrant:6333 или http://127.0.0.1:6333
      QDRANT_COLLECTION: "${QDRANT_COLLECTION:-vacancies}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TOGETHER_API_KEY: "${TOGETHER_API_KEY}"





